import { chromium, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { openSetup } from './setup-ui.mjs';
const browser = await chromium.launch({channel:'chrome',headless:true});
const page = await browser.newPage({viewport:{width:1440,height:900}});
await page.route('http://127.0.0.1:30061/**',r=>r.fulfill({body:'false'}));
try {
 await page.goto('http://127.0.0.1:5174');
 await expect(page.getByLabel('Project name',{exact:true})).toHaveAttribute('placeholder','Click here to name your project');
 await expect(page.getByRole('button',{name:'Play rules',exact:true})).toHaveCount(1);
 await expect(page.locator('.safety-bar').getByRole('button',{name:'Play rules',exact:true})).toBeVisible();
 await expect(page.locator('.safety-bar').getByRole('button',{name:/STOP ROBOT/})).toBeVisible();
 await page.getByLabel('Project name',{exact:true}).fill('Slider test');
 await page.getByLabel('Action 1 type',{exact:true}).selectOption('move');
 await page.getByLabel('Action 1 movement mode',{exact:true}).selectOption('follow');
 await page.getByRole('slider',{name:'Follow speed % slider',exact:true}).fill('40');
 await expect(page.getByRole('spinbutton',{name:'Follow speed %',exact:true})).toHaveValue('40');
 await page.getByRole('spinbutton',{name:'Follow speed %',exact:true}).fill('25');
 await expect(page.getByRole('slider',{name:'Follow speed % slider',exact:true})).toHaveValue('25');
 await page.locator('.action-fields details > summary').click();
 await page.getByRole('slider',{name:'Center tolerance % slider',exact:true}).fill('20');
 await page.getByRole('spinbutton',{name:'Steering sensitivity %',exact:true}).fill('65');
 await page.getByRole('spinbutton',{name:'Rule confidence value',exact:true}).fill('75');
 await expect(page.getByRole('slider',{name:'Rule confidence',exact:true})).toHaveValue('75');
 const downloading = page.waitForEvent('download');
 await page.getByRole('button',{name:'Save project',exact:true}).click();
 const saved = JSON.parse(await readFile(await (await downloading).path(),'utf8'));
 expect(saved.name).toBe('Slider test');
 expect(saved.rules[0].confidence).toBe(.75);
 expect(saved.rules[0].actions[0].followSpeed).toBe(25);
 expect(saved.rules[0].actions[0].centerDeadZone).toBe(.2);
 expect(saved.rules[0].actions[0].steeringSensitivity).toBe(65);
 await openSetup(page,'Your robot');
 await page.getByLabel('Robot',{exact:true}).selectOption('hummingbird');
 await page.getByRole('button',{name:'Add rule',exact:true}).click();
 await page.getByRole('slider',{name:'Action 1 brightness slider',exact:true}).fill('55');
 await expect(page.getByRole('spinbutton',{name:'Action 1 brightness',exact:true})).toHaveValue('55');
 await page.getByLabel('Action 1 type',{exact:true}).selectOption('positionServo');
 await page.getByRole('spinbutton',{name:'Action 1 angle',exact:true}).fill('125');
 await expect(page.getByRole('slider',{name:'Action 1 angle slider',exact:true})).toHaveValue('125');
 console.log('Mockup UI passed: inline naming, single bottom Play/STOP, paired slider synchronization and exact exported values, Hummingbird brightness/angle.');
} finally { await browser.close(); }
